# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    #branches: [ master ]
  pull_request:
    #branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Configure the board matrix
    strategy:
      fail-fast: false
      matrix:
        board: [
          "multi4in1:avr:multiatmega328p:bootloader=none", 
          "multi4in1:avr:multiatmega328p:bootloader=optiboot", 
          "multi4in1:avr:multixmega32d4", 
          "multi4in1:stm32f1:multi5in1t18int", 
          "multi4in1:stm32f1:multistm32f103cb:debug_option=none", 
          "multi4in1:stm32f1:multistm32f103cb:debug_option=native", 
          "multi4in1:stm32f1:multistm32f103cb:debug_option=ftdi", 
          "multi4in1:stm32f1:multistm32f103c8:debug_option=none"
        ]

    # Set the environment variables
    env:
      BOARD: ${{ matrix.board }}
      IDE_VERSION: 1.8.19
      IDE_VERSION_2: 2.0.3

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
      
      - name: Install Arduino IDE v1
        run: | 
          wget -nv http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
          tar xf arduino-$IDE_VERSION-linux64.tar.xz
          mv arduino-$IDE_VERSION $HOME/arduino-ide-v1

      - name: Install Arduino IDE v2
        run: | 
          wget -nv https://downloads.arduino.cc/arduino-ide/arduino-ide_${IDE_VERSION_2}_Linux_64bit.zip
          unzip -q arduino-ide_${IDE_VERSION_2}_Linux_64bit.zip
          mv arduino-ide_${IDE_VERSION_2}_Linux_64bit $HOME/arduino-ide-v2

      - name: Configure Build Environment
        run: |
          arduino-cli core update-index
          if [[ "$BOARD" =~ "multi4in1:avr:" ]]; then
            arduino-cli core install arduino:avr;
          fi

          if [[ "$BOARD" =~ "multi4in1:stm32f1:" ]]; then
            wget --no-verbose https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/download/v8.3.1-1.4/xpack-arm-none-eabi-gcc-8.3.1-1.4-linux-x64.tar.gz
            tar xzf xpack-arm-none-eabi-gcc-8.3.1-1.4-linux-x64.tar.gz
            mv xpack-arm-none-eabi-gcc-8.3.1-1.4 $HOME/xpack-arm-none-eabi-gcc-8.3.1-1.4
          fi
          
          mkdir -p $HOME/arduino-ide/hardware/multi4in1/
          cp -r ${GITHUB_WORKSPACE}/source/avr $HOME/arduino-ide/hardware/multi4in1/avr
          cp -r ${GITHUB_WORKSPACE}/source/stm32 $HOME/arduino-ide/hardware/multi4in1/stm32f1
          
          mkdir -p $HOME/Arduino/
          ln -s $HOME/arduino-ide/hardware $HOME/Arduino/hardware
          
          chmod +x ${GITHUB_WORKSPACE}/buildroot/bin/*
          echo "${GITHUB_WORKSPACE}/buildroot/bin" >> $GITHUB_PATH
          
      - name: Clone MULTI-Module firmware source
        run: git clone https://github.com/pascallanger/DIY-Multiprotocol-TX-Module.git

      - name: Configure MULTI-Module firmware options
        run: |
          A7105_PROTOCOLS=$(sed -n 's/[\/\/]*[[:blank:]]*#define[[:blank:]]*\([[:alnum:]_]*_A7105_INO\)\(.*\)/\1/p' DIY-Multiprotocol-TX-Module/Multiprotocol/_Config.h)
          CC2500_PROTOCOLS=$(sed -n 's/[\/\/]*[[:blank:]]*#define[[:blank:]]*\([[:alnum:]_]*_CC2500_INO\)\(.*\)/\1/p' DIY-Multiprotocol-TX-Module/Multiprotocol/_Config.h)
          CYRF6936_PROTOCOLS=$(sed -n 's/[\/\/]*[[:blank:]]*#define[[:blank:]]*\([[:alnum:]_]*_CYRF6936_INO\)\(.*\)/\1/p' DIY-Multiprotocol-TX-Module/Multiprotocol/_Config.h)
          NRF24L01_PROTOCOLS=$(sed -n 's/[\/\/]*[[:blank:]]*#define[[:blank:]]*\([[:alnum:]_]*_NRF24L01_INO\)\(.*\)/\1/p' DIY-Multiprotocol-TX-Module/Multiprotocol/_Config.h)
          CCNRF_INO_PROTOCOLS=$(sed -n 's/[\/\/]*[[:blank:]]*#define[[:blank:]]*\([[:alnum:]_]*_CCNRF_INO\)\(.*\)/\1/p' DIY-Multiprotocol-TX-Module/Multiprotocol/_Config.h)
          SX1276_PROTOCOLS=$(sed -n 's/[\/\/]*[[:blank:]]*#define[[:blank:]]*\([[:alnum:]_]*_SX1276_INO\)\(.*\)/\1/p' DIY-Multiprotocol-TX-Module/Multiprotocol/_Config.h)

          # Get the full set of protocols for each board
          if [[ "$BOARD" =~ "multi4in1:avr:multixmega32d4" ]]; then
            ALL_PROTOCOLS=$(echo $CYRF6936_PROTOCOLS);
          elif [[ "$BOARD" =~ "multi4in1:avr:multiatmega328p:" ]]; then
            ALL_PROTOCOLS=$(echo $A7105_PROTOCOLS $CC2500_PROTOCOLS $CYRF6936_PROTOCOLS $NRF24L01_PROTOCOLS $CCNRF_INO_PROTOCOLS);
          elif [[ "$BOARD" =~ "multi4in1:stm32f1:" ]]; then
            ALL_PROTOCOLS=$(echo $A7105_PROTOCOLS $CC2500_PROTOCOLS $CYRF6936_PROTOCOLS $NRF24L01_PROTOCOLS $CCNRF_INO_PROTOCOLS $SX1276_PROTOCOLS);
          fi

          # Disable CHECK_FOR_BOOTLOADER when not needed
          if [[ "$BOARD" == "multi4in1:avr:multiatmega328p:bootloader=none" ]]; then
            opt_disable CHECK_FOR_BOOTLOADER;
          fi

          # Trim the build down for the Atmega328p board
          if [[ "$BOARD" =~ "multi4in1:avr:multiatmega328p:" ]]; then
            opt_disable $ALL_PROTOCOLS
            opt_enable FRSKYX_CC2500_INO AFHDS2A_A7105_INO MJXQ_NRF24L01_INO DSM_CYRF6936_INO;
          fi

          # Trim the enabled protocols down for the STM32F103CB board with debugging or the STM32F103C8 board in general
          if [[ "$BOARD" == "multi4in1:stm32f1:multistm32f103cb:debug_option=ftdi" ]] || [[ "$BOARD" == "multi4in1:stm32f1:multistm32f103cb:debug_option=native" ]] || [[ "$BOARD" =~ "multi4in1:stm32f1:multistm32f103c8" ]]; then
            opt_disable $ALL_PROTOCOLS;
            opt_enable FRSKYX_CC2500_INO AFHDS2A_A7105_INO MJXQ_NRF24L01_INO DSM_CYRF6936_INO;
          fi

          # Disable PPM for the STM32 builds where serial and PPM don't fit together
          if [[ "$BOARD" == "multi4in1:stm32f1:multistm32f103cb:debug_option=none" ]] || [[ "$BOARD" == "multi4in1:stm32f1:multi5in1t18int" ]]; then
            opt_disable ENABLE_PPM;
          fi

      - name: Configuration diff
        run: |
          pushd DIY-Multiprotocol-TX-Module/
          git diff Multiprotocol/_Config.h
          popd
        
      - name: Arduino CLI Build
        run: (set -x; arduino-cli compile --build-property runtime.tools.xpack-arm-none-eabi-gcc-8.3.1-1.4.path=${HOME}/xpack-arm-none-eabi-gcc-8.3.1-1.4 -b $BOARD ${GITHUB_WORKSPACE}/DIY-Multiprotocol-TX-Module/Multiprotocol/Multiprotocol.ino)

      - name: Arduino IDE v1 Build
        run: (set -x; $HOME/arduino-ide-v1/arduino --pref runtime.tools.xpack-arm-none-eabi-gcc-8.3.1-1.4.path=${HOME}/xpack-arm-none-eabi-gcc-8.3.1-1.4 --verify --board $BOARD ${GITHUB_WORKSPACE}/DIY-Multiprotocol-TX-Module/Multiprotocol/Multiprotocol.ino)

      - name: Arduino IDE v2 Build
        run: (set -x; $HOME/arduino-ide-v2/arduino --pref runtime.tools.xpack-arm-none-eabi-gcc-8.3.1-1.4.path=${HOME}/xpack-arm-none-eabi-gcc-8.3.1-1.4 --verify --board $BOARD ${GITHUB_WORKSPACE}/DIY-Multiprotocol-TX-Module/Multiprotocol/Multiprotocol.ino)
